### ISSUE TITLE
Merge all the different versions in the different repositories into one commit

### ISSUE THREAD

**Issue by ehrrsn7** [ehrrsn7/no-toil#19]
#### From ehrrsn7/No-Toil-Task-Tracker-Old repository

> The final stage of this (v1.2) will reunite all of these different versions into one repository, BOTW-style. I'm currently messing around standalone frameworks such as Electron and Tauri, which inspired me to create a standalone application alongside the main app. The front-end application remained the same, as these support Vite out of the box, but business logic will need to be adjusted to enable the application to switch over to different backends (not sure if this can be easily done, firebase is a little too great at enabling real-time applications out of the box).
> 
> The idea of reuniting the codebase's involves working all the source code into GitHub, with the releases, issues and all the documentation being brought in from everywhere. (Potentially could I find some of the OG notes from No Toil about the application specifications?) My main motivations behind this are to bring the codebase back to being owned by No Toil (this means opening up a GitHub account for the company, providing them with the credentials and creating a private[?] repository) for the code to originate from. The company computer can then clone a specific release of the software which disables pulling any changes NOT tagged with that release. Then, if they'd like, they can browse the releases and the source code for newer versions and install them instead (which is better since newer versions don't need development runtime's).
> 
> Again, things need to be unified under "No-Toil". It's not an application I would use, it's one that I made for them. The database needs to be either localized (AKA finding a better alternative to SQLite...Potentially NoSQL, PostgreSQL or something GraphQL enabled. Firestore was an amazing solution, considering all that was needed was just the one list of entries) or owned by them (being able to switch to a Firestore Solution in the codebase — requires fully de-coupled business logic).

## TODO

- [ ] Create a new GitHub account for the No Toil company
   - [ ] Create a new repository on this account called No Toil Production.
   - [ ] Merge the codebases of each repository
      - Merge the codebases of each repository, creating a release for each version. (Nuke the commits) (name them 1.0.0, etc. without the prefix v or any -suffixes)
   - [ ] Merge the issues from each repository so that there's an archive of them.
      - Merge the issues from each repository so that there's an archive of them. ([GitHub article on how to do this](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository))
   - [ ] Set up v1.0 on the filter room computer
      - Set up v1.0 on the filter room computer (talk to brad) using the checkout command:
         [Git Checkout can be used with Git tags instead of branches](https://devconnected.com/how-to-checkout-git-tags/)
         ```
         git clone https://github.com/No-Toil-Industries/warehouse-production.git
         git checkout tags/1.0.0
         # Note that these won't exist until the previous TODO items are finished from the parent issue
         ```

**Comment by ehrrsn7** [comment]
Working on this per Brad asking if we could fix the 'Connected' message on their legacy version of the app. If we get this set up, we can streamline and simplify the git workflow and prevent the need to work so closely with the warehouse on issues like these. Similarly, if they want another developer, or if I'm unavailable for a project for them, we'll need to implement a repository with proper documentation which other people can use as reference in order to debug or develop further.

Ideas on streamlining future workflows without disrupting the current design of the program:
- maybe there could be an 'update available' button in the sidebar that appears when necessary? (follow-up, how will the client/server know if it's necessary, and how can I set up this repository on github to send this notification? this requires some research)
- same as above, can there be a 'restart server' button somewhere?
- current working paradigm: use this repository to simplify the way the environment is handled. docker or python venv are known tools for this, but in the past I was unable to utilize this in the final product. research this in order to implement this, so that debugging for brad can be simplified.
- on the 'debugging for Brad' train of thought, is there a log file system that could be implemented? requires research.

**Comment by ehrrsn7** [comment]
- [ ] Work on the 'Connected' message not working for brad
